### ISSUE TITLE
@parrychri1 playtest

### ISSUE THREAD

**Issue by Gyle** [Gyle/parrychris_OneHit_P2#33]
Game seems unbalanced. Re-evaluate dash. Too overpowered from beginning. Can spam control, giving not much point for other moves. Possible option: Give a visible cooldown/power meter which is empty at beginning of round and fills up over time. Maybe blocking a move could fill it up faster. Then meter depletes when move is use. Could help balance game.

**Comment by ZiggyNZ** [comment]
The team agrees, at the current state (last week), the dash was rather strong and jabs were somewhat redundant. We have changes planned change in order to balance this more. We're aiming to have varying dash/block durations and cooldowns (depending on the character) to incentivize / force the use of other tactics.

We have also looked into some sort of visible block / dash cooldown meter, and so far our best idea is a controller vibration, so the player cannot tell and predict your cooldowns.

We're also considering the idea of some sort of depleting block to counter turtle tactics.

Thanks for the feedback chris!
