### ISSUE TITLE
Waseem Koya - Playtest feedback

### ISSUE THREAD

**Issue by koyawase** [Gyle/parrychris_OneHit_P2#36]
* Position of the controls were very awkward and uncomfortable to play the game. I had to use my left hand for the WASD keys and my right hand crossed over and underneath my left hand for the ctrl key. Everything  just seemed to be jammed in one corner. If I used my right hand for WASD and left hand for ctrl, it wouldn't be as cramped but I am not used to using my right hand for WASD. 

* There seemed to be no use for the jab attack as the dash attack was so much better.  

* Would be nice to know when I can block. If I accidentally tapped the block for a millisecond, the block would activate and be over very quickly. Would have to wait for a much longer timer to block again, without knowing how long I need to wait

**Comment by Gyle** [comment]
Regarding the first point of controls, I do agree with Waseem. It is very awkward and uncomfortable and the work-around using right hand for WASD is not a good option as Waseem said. This is because people were brought up to use WASD with their left hand. Therefore, I will bring up the idea to remap the controls and perhaps push through the the controller support idea. This way, the controls will not be awkward and uncomfortable.

For the second point, we have received similar feedback from the Hunter prior to the play testing session. This was a feature left in by the original creator. I do see the point in how you would feel jab has no use. To address this concern, I will bring up the idea to cut the ability to jab. This is because if we have a dash with a cool down, then the player will not be fully punished for wasting the attack as they can still jab. Since this  is a mind games kind of fighting game then it makes sense to remove jab to add the challenge and punish factor.

Lastly, I do agree with Waseem's point regarding non-intuitive blocking. There is no indicator letting the player know how long they have to wait for the block cool down. As Waseem said, he accidentally tapped block and having no indicator he did not realise he could not block when he needed it. To address this issue, I will bring up to the meeting to add some nice way to indicate to the player the cool-down for their block.
